### ISSUE TITLE
shiny output?

### ISSUE THREAD

**Issue by tyokota** [Displayr/flipChart#1]
Hi! Can the output of the regression summary table to exported to shiny? I noticed that the table is rendered in the viewer, but I was not able to see where I could export the html to render in shiny.

TIA!

**Comment by mwmclean** [comment]
Can you please provide a reproducible example of an object you want to export? The tables are [htmlwidgets](https://cran.r-project.org/web/packages/htmlwidgets/index.html), so they should be displayable in shiny quite easily.
